import {
  type RouteConfig,
  index,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("settings", "routes/settings.tsx"),
  route("join/:token", "routes/join.tsx"),
  route("clubs/:clubSlug/welcome", "routes/welcome.tsx"),
  route("clubs/:clubSlug/api/chat", "routes/api.chat.ts"),
  route("clubs/:clubSlug/api/thread", "routes/api.thread.ts"),
  route("clubs/:clubSlug/api/feedback", "routes/api.feedback.ts"),
  route("clubs/:clubSlug", "routes/app-layout.tsx", [
    index("routes/club-home.tsx"),
    route("garden", "routes/garden.tsx"),
    route(
      "garden/conversations/:id",
      "routes/garden.conversations.$id.tsx",
    ),
    route("garden/projects/:id", "routes/garden.projects.$id.tsx"),
    route("garden/modules/:slug", "routes/garden.modules.$slug.tsx"),
    route("learning", "routes/learning.tsx"),
    route("learning/:slug", "routes/learning.$slug.tsx"),
    route("artifacts", "routes/artifacts.tsx"),
    route("gallery", "routes/gallery.tsx"),
    route("inspiration", "routes/inspiration.tsx"),
    route("admin", "routes/admin.tsx"),
    route("admin/members", "routes/admin.members.tsx"),
    route("admin/invitations", "routes/admin.invitations.tsx"),
    route("admin/settings", "routes/admin.settings.tsx"),
    route(
      "admin/conversations/:id",
      "routes/admin.conversations.$id.tsx",
    ),
  ]),
  route(":section", "routes/legacy.$section.tsx"),
  route(":section/*", "routes/legacy.$section.$.tsx"),
  route("login", "routes/login.tsx"),
  route("dev/login", "routes/dev.login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("auth/google", "routes/auth.google.tsx"),
  route("auth/google/callback", "routes/auth.google.callback.tsx"),
] satisfies RouteConfig;
