import {
  type RouteConfig,
  index,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("settings", "routes/settings.tsx"),
  route("admin/clubs", "routes/admin.clubs.tsx"),
  route("join/:token", "routes/join.tsx"),
  route("clubs/:clubSlug/welcome", "routes/welcome.tsx"),
  route("clubs/:clubSlug/api/chat", "routes/api.chat.ts"),
  route("clubs/:clubSlug/api/thread", "routes/api.thread.ts"),
  route("clubs/:clubSlug/api/feedback", "routes/api.feedback.ts"),
  route("clubs/:clubSlug", "routes/app-layout.tsx", [
    index("routes/club-home.tsx"),
    route("garden", "routes/garden.tsx"),
    route(
      "garden/conversations/:id",
      "routes/garden.conversations.$id.tsx",
    ),
    route("garden/projects/:id", "routes/garden.projects.$id.tsx"),
    route("garden/modules/:slug", "routes/garden.modules.$slug.tsx"),
    route("learning", "routes/learning.tsx"),
    route("learning/:slug", "routes/learning.$slug.tsx"),
    route("artifacts", "routes/artifacts.tsx"),
    route("gallery", "routes/gallery.tsx"),
    route("inspiration", "routes/inspiration.tsx"),
    route("settings/connections", "routes/settings.connections.tsx"),
    route("admin", "routes/admin.tsx"),
    route("admin/members", "routes/admin.members.tsx"),
    route("admin/invitations", "routes/admin.invitations.tsx"),
    route("admin/settings", "routes/admin.settings.tsx"),
    route(
      "admin/conversations/:id",
      "routes/admin.conversations.$id.tsx",
    ),
  ]),
  route("join", "routes/join.tsx"),
  route("welcome", "routes/welcome.tsx"),
  route("api/chat", "routes/api.chat.ts"),
  route("api/thread", "routes/api.thread.ts"),
  route("api/feedback", "routes/api.feedback.ts"),
  route("api/artifact-uploads", "routes/api.artifact-uploads.ts"),
  route("api/artifact-uploads/:uploadId/files", "routes/api.artifact-uploads.$uploadId.files.ts"),
  route("api/artifact-uploads/:uploadId/finalize", "routes/api.artifact-uploads.$uploadId.finalize.ts"),
  route("api/artifact-uploads/:uploadId/abort", "routes/api.artifact-uploads.$uploadId.abort.ts"),
  route("api/artifacts/links", "routes/api.artifacts.links.ts"),
  route("api/artifacts/:artifactId/link-version", "routes/api.artifacts.$artifactId.link-version.ts"),
  route("api/artifacts/:artifactId/restore-version", "routes/api.artifacts.$artifactId.restore-version.ts"),
  route("api/artifacts/:artifactId/gallery", "routes/api.artifacts.$artifactId.gallery.ts"),
  route("api/artifacts/:artifactId/capability", "routes/api.artifacts.$artifactId.capability.ts"),
  route("api/artifacts/:artifactId", "routes/api.artifacts.$artifactId.ts"),
  route(":section", "routes/legacy.$section.tsx"),
  route(":section/*", "routes/legacy.$section.$.tsx"),
  route("login", "routes/login.tsx"),
  route("review/login", "routes/review.login.tsx"),
  route("connect", "routes/connect.tsx"),
  route("privacy/mcp", "routes/privacy.mcp.tsx"),
  route("authorize", "routes/oauth.authorize.tsx"),
  route("dev/login", "routes/dev.login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("auth/google", "routes/auth.google.tsx"),
  route("auth/google/callback", "routes/auth.google.callback.tsx"),
] satisfies RouteConfig;
